### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by pavelBy** [schneidmaster/sitemap-webpack-plugin#13]
Hi, I followed your manual, but on a webpack compilation step I receive an error "SitemapPlugin is not a constructor"

**Comment by schneidmaster** [comment]
Hi, please post your webpack config file. If you are not using babel, note that the plugin is exported on `default` so you will need e.g. `const SitemapWebpackPlugin = require('sitemap-webpack-plugin').default;`.

**Comment by pavelBy** [comment]
Zach thank you, the `const SitemapWebpackPlugin = require('sitemap-webpack-plugin').default;` it's work

**Comment by schneidmaster** [comment]
No problem, glad you got it working.

**Comment by rootlinux2** [comment]
because I'm using it in an ESM module I need to use import instead of require

`import { default as SitemapPlugin } from "sitemap-webpack-plugin";`

but I'm facing this error

`GLOBAL ERR:  SitemapPlugin is not a constructor`
