### ISSUE TITLE
ReferenceError: SitemapPlugin is not defined

### ISSUE THREAD

**Issue by jamiecarter7** [schneidmaster/sitemap-webpack-plugin#18]
Hi,

I am getting this error.

`ReferenceError: SitemapPlugin is not defined`

My prod.build.config.js

```
const SitemapWebpackPlugin = require('sitemap-webpack-plugin').default;

/* Other stuff */

plugins: [
    new SitemapPlugin('https://mysite.com', prerenderRoutes)
]
```
Im using webpack 3 if that helps

**Comment by schneidmaster** [comment]
You've named the variable `SitemapWebpackPlugin` when requiring it, but then are trying to invoke it as `SitemapPlugin`. You'll need to change one or the other so they're the same.

**Comment by jamiecarter7** [comment]
Just so you know.
I copied this straight from the readme file. 
I dont know how wp4 works so I could be wrong.

**Comment by schneidmaster** [comment]
Yeah I noticed the README had an inconsistent variable name for the non-babel example so I just fixed that. This isn't related to webpack 3 vs. 4 -- it's just how Javascript works (and pretty much all programming languages), you've got to use the same name when you define the variable that you use when you reference it 🙂
