### ISSUE TITLE
Suggestion for improvement

### ISSUE THREAD

**Issue by milewski** [schneidmaster/sitemap-webpack-plugin#21]
Hi can you consider migrating out the current implementation to use  this lib instead [https://www.npmjs.com/package/sitemap](https://www.npmjs.com/package/sitemap) for generating the sitemap? the current implementation only support a very limited range of what a sitemap can offer... specially when it comes down to multi-language website

**Comment by schneidmaster** [comment]
Hi there! I'd be happy to accept a PR implementing that change. I'd prefer to keep the existing API intact though to avoid churn (and add additional options to the existing third `options` argument).
