### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by ErinMorelli** [schneidmaster/sitemap-webpack-plugin#22]
I'm encountering this error when I attempt to use the plugin:

```
/PATH/TO/node_modules/sitemap-webpack-plugin/lib/index.js:121
      compiler.hooks.emit.tapAsync('sitemap-webpack-plugin', function (compilation, callback) {
                     ^

TypeError: Cannot read property 'emit' of undefined
    at SitemapWebpackPlugin.apply (/PATH/TO/node_modules/sitemap-webpack-plugin/lib/index.js:121:22)
```

**Comment by schneidmaster** [comment]
Hi there -- what version of webpack and sitemap-webpack-plugin are you using? For webpack 4, use version 0.6 or greater; for webpack <= 3, you must use version 0.5.x. (That error sounds like you may be using webpack <=3 + webpack-sitemap-plugin 0.6, as the `compiler.hooks.emit` signature was introduced in webpack 4.)

**Comment by ErinMorelli** [comment]
Ah that was it! Upgraded my webpack to 4 and every thing is working - thanks!
