### ISSUE TITLE
Custom Output path

### ISSUE THREAD

**Issue by imbudhiraja** [schneidmaster/sitemap-webpack-plugin#23]
How we can specify the output path

**Comment by schneidmaster** [comment]
The sitemap is emitted to the same path as the rest of the assets from the webpack build. You can specify the overall output path within the [webpack configuration](https://webpack.js.org/configuration/output/#outputpath).

**Comment by agordeev** [comment]
@schneidmaster what if I want to put sitemap on the root, but have the rest of assets in `dist` folder?

**Comment by cansin** [comment]
Exactly, I have a similar use case where I'd like to set a separate output path. I tried given an absolute path to `fileName` but that did not help.
