### ISSUE TITLE
sitemapindex

### ISSUE THREAD

**Issue by bardiaheshmati** [schneidmaster/sitemap-webpack-plugin#30]
Is there any way to generate sitemap indices using this plugin ?

**Comment by schneidmaster** [comment]
Not currently. I'd be happy to accept a PR for this, shouldn't be too hard as it is [supported by the underlying sitemap library](https://www.npmjs.com/package/sitemap#create-sitemap-and-index-files-from-one-large-list).

**Comment by schneidmaster** [comment]
Published 0.8.0 which automatically generates a sitemap index if you provide more than 50,000 paths
