### ISSUE TITLE
Is it sitemap generated in dev mode?

### ISSUE THREAD

**Issue by devalexqt** [schneidmaster/sitemap-webpack-plugin#31]
I'm using webpack dev server (webpack-dev-server) for development and can't found sitemap.xml file on dev server is it only generated in production? To list of all available files I open page: http://localhost:9000/webpack-dev-server but sitemap not found. So where is sitemap file located?

**Comment by schneidmaster** [comment]
Yes, the sitemap is generated in development. The location will depend on the rest of your webpack configuration. If your output publicPath is `/` then it will probably just be at http://localhost:9000/sitemap.xml (assuming 9000 is the port that you're running webpack-dev-server on).
