### ISSUE TITLE
[Feature Request] Support for hreflang

### ISSUE THREAD

**Issue by Jaimies** [schneidmaster/sitemap-webpack-plugin#35]
Seems like there is no way to use [hreflang](https://support.google.com/webmasters/answer/189077) with this plugin. It would be great to have such functionality.

**Comment by schneidmaster** [comment]
This is already supported. I just pushed up a [test case](https://github.com/schneidmaster/sitemap-webpack-plugin/blob/master/test/success-cases/multi-language/webpack.config.js) with an example configuration. (This library uses the `sitemap` npm package under the hood, so any of their [documented options](https://www.npmjs.com/package/sitemap#options-you-can-pass) should just work.)

**Comment by Jaimies** [comment]
Thanks. Maybe this feature should be mentioned in Readme?

**Comment by schneidmaster** [comment]
The README does [mention](https://github.com/schneidmaster/sitemap-webpack-plugin#options) that you can use any other options from the `sitemap` library. There's a lot of different possible options and use cases so I'm not sure it adds anything to recreate the `sitemap` library docs in this repo's README.
