### ISSUE TITLE
Option for lastmod to use the last modified time for said file. 

### ISSUE THREAD

**Issue by ChildishGiant** [schneidmaster/sitemap-webpack-plugin#38]
[fs.stat can provide this](https://nodejs.org/api/fs.html#fs_stats_mtime). Not sure if that'd replace how true works

**Comment by schneidmaster** [comment]
I'm not really sure how this could work, for a couple of reasons:

1. With a standard webpack build, the mtime of all of the output files will be whenever the build is run -- the files don't exist in a long-running or static form, they are usually regenerated from the source code on each build.
2. In many cases there are not actually output files to check at all -- for example your site might use react-router and routing is done dynamically.

Could you provide more details about how you would envision this working?

**Comment by ChildishGiant** [comment]
For me some pages are static and only some handled by webpack. Also to my knowledge a page is only rebuilt if there were changes since last build (although I could be wrong on that). Maybe an options object with an array of which files to look at?

**Comment by schneidmaster** [comment]
> For me some pages are static and only some handled by webpack.

I think this is best handled in user configuration. For the paths that you know are static, you can run the `fs.stat` in your webpack config file and provide the result as the `lastMod` to each path, e.g. the [object paths example](https://github.com/schneidmaster/sitemap-webpack-plugin#example-webpackconfigjs)

> Also to my knowledge a page is only rebuilt if there were changes since last build

This depends a lot on your specific configuration and which framework (if any) you are using. I don't believe that the webpack plugin API exposes this information in a way that the sitemap plugin could automatically infer what's changed.
