### ISSUE TITLE
Build error: ReferenceError: out is not defined

### ISSUE THREAD

**Issue by eb-drocha** [schneidmaster/sitemap-webpack-plugin#4]
When running webpack with the SitemapPlugin I get the following error:
`
...../node_modules/sitemap-webpack-plugin/index.js:95
          return Buffer.byteLength(out, 'utf8');
`
I've looked into the source code and it seems that "out" variable is not defined.
I'm using version 0.2.0 of sitemap-webpack-plugin. Can you check please?

**Comment by schneidmaster** [comment]
Hi, thanks for the report. This was accidentally introduced during some unrelated recent work and is fixed in 0.2.2.
