### ISSUE TITLE
Add dynamic routes to the sitemap

### ISSUE THREAD

**Issue by Menna-Elgohary** [schneidmaster/sitemap-webpack-plugin#42]
How can I add dynamic routes to the sitemap?

**Comment by schneidmaster** [comment]
Hi there! It depends on the data source -- you would basically need to query the full list of paths within your webpack config and provide those as the paths. Truly dynamic routes (i.e. you don't know all of the routes at deploy time) are not really compatible with a sitemap which by necessity is a static file.
