### ISSUE TITLE
Provide base URL is not a string

### ISSUE THREAD

**Issue by amrfhn** [schneidmaster/sitemap-webpack-plugin#46]
Hi, 

I have configured based on the documentation. When I run npm run serve, I got this error 'Provide base URL is not a string'.

<img width="889" alt="Capture" src="https://user-images.githubusercontent.com/46885852/107505551-d3c55e00-6bd7-11eb-956d-7f5c9b1b44c5.PNG">
<img width="485" alt="Capture1" src="https://user-images.githubusercontent.com/46885852/107505635-f788a400-6bd7-11eb-9681-74c38eaff146.PNG">

**Comment by schneidmaster** [comment]
Hi! What version of the plugin are you using? Your configuration looks correct if you're on 1.0 but the error message indicates you're on 0.x.

**Comment by amrfhn** [comment]
I am using 0.7.1. But if I install the latest version 1.0.0, I receive this error.

<img width="201" alt="Capture" src="https://user-images.githubusercontent.com/46885852/107519210-f1e88980-6bea-11eb-88f0-01afa461eca1.PNG">

**Comment by schneidmaster** [comment]
That probably implies an issue with one of your `paths`, can you share what you're using for the paths value?

**Comment by amrfhn** [comment]
I used dummy paths data and declare it straight in the same file, like this:

```
const paths = [
  '/',  
  'foo/',
  'bar/'
];
```
 In order to see if it can run and generate the XML data.

<img width="613" alt="Capture" src="https://user-images.githubusercontent.com/46885852/107607643-c4482280-6c74-11eb-8b42-de23811586d0.PNG">

**Comment by schneidmaster** [comment]
Ah I see. The problem is that your paths need to begin with a `/` to be valid. Otherwise you'd get sitemap URLs like `https://www.yoursite.comfoo/`.

**Comment by amrfhn** [comment]
Ahha ~ gotcha! Solved the issue.
And I need to use a valid base URL, which needs to have 'HTTP' even I use it for localhost.

<img width="526" alt="Capture" src="https://user-images.githubusercontent.com/46885852/107662041-d782de80-6cc4-11eb-94f0-2d2209d4660e.PNG">
<img width="885" alt="Capture1" src="https://user-images.githubusercontent.com/46885852/107662045-d8b40b80-6cc4-11eb-9342-0c7efd0cfa47.PNG">

Thanks, man!

**Comment by schneidmaster** [comment]
No problem! I'll see if I could present that second error a bit more helpfully.
