### ISSUE TITLE
Dynamic baseurl

### ISSUE THREAD

**Issue by PatricioIN** [schneidmaster/sitemap-webpack-plugin#61]
Hi there.

My app works in differents domain. I need get the current host and set de param "base" with the url.

Is it possible?

```
 new SitemapPlugin({
                base: myCurrentHost,
                paths: ...
})
```

**Comment by schneidmaster** [comment]
Hi! Webpack assets are statically built when you deploy your application, so you can't use a webpack plugin with different data based on specific request parameters.
